version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech123
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg://fintech:fintech123@db:5432/fintech
      GEMINI_API_URL: https://generativelanguage.googleapis.com/v1beta/openai/
      GEMINI_API_KEY: AkashGaurav-2026-07-23T00:00:00.000000Z
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  db_data:
